export interface AbetarjaPage {
  pageNumber: number
  title: string
  letters?: string
  text: string[]
  imageDescription: string
  handwriting?: string
}

export const ABETARJA_PAGES: AbetarjaPage[] = [
  {
    pageNumber: 1,
    title: "Gjuha Jonë / Abetare",
    text: [
      "GJUHA JONË",
      "",
      "Gjuha jonë sa e mirë!",
      "Sa e ëmbël, sa e gjerë!",
      "Sa e lehtë, sa e lirë",
      "Sa e bukur, sa e vlere!",
      "— Naim Frashëri",
      "",
      "ABETARE",
      "",
      "Are, are, abetare,",
      "Në çdo faqe një dritare,",
      "Po më çel ti për çdo ditë,",
      "E më jep gëzim e dritë.",
      "Ore, ore, oj fletore,",
      "Ca me vija, ca katrore.",
      "Do t'ju shkruaj me vija të lira,",
      "Do t'ju mbush me nota të mira.",
      "— Bekim Gaçe",
    ],
    imageDescription:
      "Busti i Naim Frashërit mbi një piedestal guri, me lule e pemë rreth tij.",
  },
  {
    pageNumber: 2,
    title: "Shkronja Aa dhe Nn",
    letters: "Aa  Nn",
    text: [
      "A Ana! A Ana! A Ana!",
      "Na, Ana. Na, na, na, na.",
      "",
      "A A A A A A A A",
      "a a a a a a a a",
      "N N N N N N N N",
      "n n n n n n n n",
    ],
    imageDescription:
      "Një djalë mban një fije në formë shkronje A, me gërshërë e pe pranë. Një vajzë qëndron pranë shkronjës N.",
  },
  {
    pageNumber: 3,
    title: "Shkronja Ee dhe Ii",
    letters: "Ee  Ii",
    text: [
      "Ena e Ana.",
      "Ana e ena. Ne e Ana.",
      "",
      "Ai e Nina.",
      "Ta ia ia! Nina: ia ia ia!",
    ],
    imageDescription:
      "Dy gra në kuzhinë: njëra gatuan, tjetra mbikëqyr. Një burrë, një vajzë dhe një kalë duke lëruar arën.",
  },
  {
    pageNumber: 4,
    title: "Shkronja Ëë dhe Uu",
    letters: "Ëë  Uu",
    text: [
      "Ani, na enën.",
      "Ani, Nani e Ana në…",
      "",
      "Unë e ai në…",
      "Ai e unë në…",
    ],
    imageDescription:
      "Një vajzë me fustan blu dhe një djalë arrijnë drejt shkronjës Ëë. Një tren i gjelbër. Një autobus i kuq mbi një urë.",
  },
  {
    pageNumber: 5,
    title: "Shkronja Rr dhe Mm",
    letters: "Rr  Mm",
    text: [
      "Rina ura",
      "Rina në urë. Urani i ra.",
      "",
      "Mira miu",
      "Miau, miau, miau. Miri e muri.",
      "Mira e Miri me murin e ri.",
    ],
    imageDescription:
      "Fëmijë duke luajtur me kube. Rina ulet mbi kube, një djalë shkelmon topin. Mira e Miri ndërtojnë murin me kube.",
  },
  {
    pageNumber: 6,
    title: "Shkronja Tt dhe Oo — Teuta e Artani",
    letters: "Tt  Oo",
    text: [
      "TEUTA E ARTANI",
      "",
      "Teuta mori me…",
      "Artan, na… të mirë.",
      "— Teuta, Artan, eni te nëna!",
      "Nëna mori Teutën e Artanin në…",
      "Ata i uruan natë të mirë.",
    ],
    imageDescription:
      "Një vajzë e një djalë në shtretërit e tyre. Nëna qëndron te dera me përparëse.",
  },
  {
    pageNumber: 7,
    title: "Shkronja Ll — Te Lulet e Mia",
    letters: "Ll",
    text: [
      "TE LULET E MIA",
      "",
      "Liria luan me Luanin.",
      "— Lule, a luan ti me ne?",
      "— Luli luan me mua, e ti me Lirinë.",
      "— Mirë, Lule. Eni te lulet e mia.",
      "Ata te lulet e Luanit.",
    ],
    imageDescription:
      "Fëmijë duke luajtur në park: dy fëmijë hedhin topin, njëri në lëkundëse. Lule rreth gardhit.",
    handwriting: "l l l  lule lule lule",
  },
  {
    pageNumber: 8,
    title: "Shkronja Kk — Kali i Mirakut",
    letters: "Kk",
    text: [
      "KALI I MIRAKUT",
      "",
      "Miraku ka kalë. Kali i Mirakut iku në mal.",
      "Miraku e Leka e kërkuan kalin.",
      "— O, kali im!",
      "— Ku ike, o kalë?",
      "Miraku e Leka e morën kalin.",
    ],
    imageDescription:
      "Dy djem vrapojnë në fushë. Kali kullot në sfond. Pemë e shkurre rreth tyre.",
    handwriting: "k k k  kali kali kali  kam ke ka kemi keni kanë",
  },
  {
    pageNumber: 9,
    title: "Shkronja Hh — Hëna",
    letters: "Hh",
    text: [
      "HËNA",
      "",
      "— Hëna, hëna! Eni, eni!",
      "Hëna lart.",
      "— O, hëna! Nënë, hëna!",
      "— Hekuran, Krenare, eni më te nëna!",
      "— Mirë, nënë, mirë! Hëna lart e ti me ne.",
    ],
    imageDescription:
      "Tri personazhe në një fshat: një grua me shami mban duart e dy fëmijëve. Hëna në qiell.",
    handwriting: "h h h  hëna hëna hëna  koha hiri huri",
  },
  {
    pageNumber: 10,
    title: "Shkronja Pp — Pulat e Petritit",
    letters: "Pp",
    text: [
      "PULAT E PETRITIT",
      "",
      "Petriti ka plot pula.",
      "Pulat kanë pupla.",
      "— Pulë-pulë-pulë! — ua pret Petriti.",
      "— Ko-ko-ko! Ki-ki-ki!",
      "— Eni, pula, eni te unë!",
      "— Ko-ko-ko! Ki-ki-ki!",
      "Pulat hapin krahët.",
      "— Hani, hani, pulat e mia!",
    ],
    imageDescription:
      "Petriti ushqen pulat. Pula, zoga, një gjel mbi cung. Një shtëpi e pemë në sfond.",
    handwriting: "p p p  pula pula pula  pata peta pema patatet",
  },
  {
    pageNumber: 11,
    title: "Shkronja Jj — Jehona me Jakë",
    letters: "Jj",
    text: [
      "JEHONA ME JAKË",
      "",
      "Jehona ka jakë. Ajo e punoi jakën me makinë.",
      "— Jehonë, ma jep atë jakë! — ia kërkoi Jeta.",
      "— Jo, Jetë, unë të punoj jakë tjetër.",
      "Jeta e Jehona kanë jaka të mira.",
    ],
    imageDescription:
      "Një vajzë shikon në pasqyrë, një grua qep me makinë.",
    handwriting: "j j j  jaka jaka jaka  Ne luajmë me top.",
  },
  {
    pageNumber: 12,
    title: "Shkronja Dd — Drita e Dritani",
    letters: "Dd",
    text: [
      "DRITA E DRITANI",
      "",
      "Drita e Dritani e duan dajë Dautin.",
      "Dajë Dauti ka plot dele.",
      "Ata nderuan dajën:",
      "— Mirëdita, daja Daut!",
      "— Mirëdita, Dritë e Dritan! Eni te daja!",
      "— Dajë, kur dalin delet në mal?",
      "— Delet dalin përditë në mal.",
      "— Mirë, pra, ne dalim të dielën me dele.",
    ],
    imageDescription:
      "Fëmijë vizitojnë xhaxhain që ulet pranë kopesë me dele.",
    handwriting: "d d  dora dera dritarja  druri durimi deti e diel",
  },
  {
    pageNumber: 13,
    title: "Shkronja Bb — Blerimi e Blerina",
    letters: "Bb",
    text: [
      "BLERIMI E BLERINA",
      "",
      "Blerimi e Blerina këndojnë bukur.",
      "Ata janë bilbilat tanë.",
      "Blerimi e Blerina këndojnë për ne.",
      "Blerimi e Blerina do të këndojnë në radio.",
    ],
    imageDescription:
      "Dy fëmijë këndojnë në mikrofon mbi skenë. Publiku i shikon.",
    handwriting: "B b  bilbili i bukur  Bamiri bleu bukë.",
  },
  {
    pageNumber: 14,
    title: "Shkronja Ff — Fabrika e Punëtorët",
    letters: "Ff",
    text: [
      "FABRIKA E PUNËTORËT",
      "",
      "Në fabrikën tonë punojnë punëtorët.",
      "Puna me makina bëhet më lehtë.",
      "Babai i Fatonit punon e fiton për fëmijët e tij të mirë.",
      "Fatoni krenohet për babanë e tij punëtor.",
    ],
    imageDescription:
      "Dy punëtorë në fabrikë: njëri punon me makinë të gjelbër, tjetri qëndron pranë strukturave të kuqe.",
    handwriting: "F f  flutura flamuri  Fatoni e pa fabrikën",
  },
  {
    pageNumber: 15,
    title: "Shkronja Cc — Ceni e Leci",
    letters: "Cc",
    text: [
      "CENI E LECI",
      "",
      "— Cak-cak-cak! — trokiti Leci në dritaren e Cenit.",
      "Nëna doli.",
      "— Mirëdita! — nderoi djali nënën e Cenit.",
      "— Mirëdita! Cili je ti?",
      "— Unë jam Leci.",
      "— Leci? O, eja brenda. Djali im, Ceni, bëri më mirë.",
      "— Dua t'i jap Cenit këto pemë.",
      "— Mirë, falemnderit! Eja te Ceni.",
      "Leci e pa mikun e tij, Cenin.",
    ],
    imageDescription:
      "Një grua me fustan të kuq dhe një djalë me shportë frutash pranë shtratit ku shtrihet Ceni.",
    handwriting: "C c  Cak-cak-cak trokiti Leci.",
  },
  {
    pageNumber: 16,
    title: "Shkronja Ss — Saksitë e Samirës",
    letters: "Ss",
    text: [
      "SAKSITË E SAMIRËS",
      "",
      "Sa lule të bukura ka Samira! Në dritaren e saj duken plot saksi.",
      "— Samirë, ku i more këto saksi me lule? — iu drejtua Suta.",
      "— I bleu nëna, por unë kujdesem për to.",
      "— Sa të bukura janë saksitë e tua! E kanë stolisur dritaren për bukuri.",
    ],
    imageDescription:
      "Dy vajza me saksi lulesh. Njëra me fustan blu pranë dritares, tjetra me fustan të kuq ujit lulet.",
    handwriting: "S s  Samira e saksitë",
  },
  {
    pageNumber: 17,
    title: "Shkronja Çç — Çekiçi më i Rëndë",
    letters: "Çç",
    text: [
      "ÇEKIÇI MË I RËNDË",
      "",
      "Çerkini punon çdo ditë me çekiç.",
      "— Çak-çuk! Çak-çuk! — i bie ai hekurit.",
      "Duart e Çerkinit janë të forta.",
      "Çeljeta e Çelikani krenohen për babanë punëtor.",
      "Çerkini ka plot çekiçë.",
      "— O, baba, ti me këtë çekiç drejton çdo hekur! — foli Çelikani.",
      "— Çoje pak atë çekiç, — ia priti babai.",
      "— O, çfarë çekiçi! — u habit Çelikani.",
    ],
    imageDescription:
      "Çerkini punon me çekiç mbi hekur. Dy fëmijë qëndrojnë pranë duke shikuar.",
    handwriting: "Ç ç  Çerkini punon me çekiç.",
  },
  {
    pageNumber: 18,
    title: "Shkronja LLll — Halla e Filloreta",
    letters: "LLll",
    text: [
      "HALLA E FILLORETA",
      "",
      "Halla e Filloretës i do llokumët e ëmbla.",
      "— Hallë, të solla plot llokume.",
      "— Oh, loçka e hallës! Ti je llokumi im më i ëmbël, — ia priti halla.",
      "Filloreta e pa hallën me plot mirësi.",
      "Halla i fali Filloretës disa sende për lojë.",
    ],
    imageDescription:
      "Një vajzë i jep hallës një pjatë me ëmbëlsira. Një orë varur në mur.",
    handwriting: "Ll ll  Llamba ndriçon.",
  },
  {
    pageNumber: 19,
    title: "Shkronja Yy — Në Pyll",
    letters: "Yy",
    text: [
      "NË PYLL",
      "",
      "— Yllka, eja me ne!",
      "— Eja, Ylber, po nisemi!",
      "— Po ku mbeti Yllnorja?",
      "— Ja, me Yllin.",
      "— O, eni, eni sa më parë! Po nisemi drejt në pyll.",
      "Fëmijët u nisën.",
      "— Oh, pylli, pylli! — bërtitën ata posa iu afruan.",
      "— Sa i bukur ky pylli ynë!",
      "Aty fëmijët takuan bariun me dele. Ai i ra fyellit.",
      "Fëmijët luajtën e kërcyen. Mandej, në pyll panë plot lule.",
      "Ata bënë tufa me lule të bukura.",
      "— Mrekulli! — foli Yllnorja. — Kaluam dy orë të bukura në pyll.",
    ],
    imageDescription:
      "Fëmijë në pyllin e gjelbër. Një vajzë zgjat dorën, një djalë tregon rrugën.",
    handwriting: "Y y  Ylli ylli Ylberina.",
  },
  {
    pageNumber: 20,
    title: "Shkronja Gg — Goma e Gencit",
    letters: "Gg",
    text: [
      "GOMA E GENCIT",
      "",
      "Genci përdori gomën në tërë fletoren e tij.",
      "Fletorja e Gencit u ndy fund e krye.",
      "— Genc, kur gabon përdore gomën! — e porositi Agroni.",
      "Genci pa fletoren e ndytë, mandej pa fletoren e pastër të Agronit.",
      "— Tani, gomën do ta përdor fare pak, — premtoi Genci.",
    ],
    imageDescription:
      "Dy nxënës ulen në bankë: njëri me fletore të ndotur, tjetri shkruan në faqe të pastër.",
    handwriting: "G g  Genci goma gabimi",
  },
  {
    pageNumber: 21,
    title: "Shkronja RRrr — Rrota në Gropë",
    letters: "RRrr",
    text: [
      "RROTA NË GROPË",
      "",
      "— Urra! — bërtasin Rroni, Rrita e Curri.",
      "— Traktori i ri po kalon nëpër katundin tonë.",
      "Mirëpo, rrota e traktorit ra në gropë e nuk eci më.",
      "— Ndihmë! Ejani, o burra! — bërtitën prapë fëmijët.",
      "Fëmijët e burrat ndihmuan traktoristin.",
      "Rrota e traktorit doli nga gropa e u nis.",
      "— Ju falemnderit! — iu drejtua traktoristi plot hare.",
      "— Rruga e mbarë! — bërtitën fëmijët e u nisën në oborrin e Currit për të luajtur me rrota.",
    ],
    imageDescription:
      "Një traktor i kuq i ngecur në gropë. Fëmijë ndihmojnë traktoristin ta nxjerrin.",
    handwriting: "Rr rr  Rroni rrota oborri",
  },
  {
    pageNumber: 22,
    title: "Shkronja SHsh — Shokët",
    letters: "SHsh",
    text: [
      "SHOKËT",
      "",
      "Shega e Mirashi janë shokë të mirë.",
      "Ata shkojnë bashkë në shkollë.",
      "Ata ulen në bankën e parë.",
      "Mirashi u mahit me Shegën:",
      "— Shegë, a të kanë këputur ty nga dega e shegës?",
      "Shega bërtiti befas:",
      "— Mirash, ti nuk je shok!",
      "Mirashi i kërkoi falje. I tregoi se shokët bëjnë ngapak shaka.",
      "— Mirë, pra, — foli atëherë Shega — shakaja është shaka. Ne jemi prapë shokë të mirë.",
    ],
    imageDescription:
      "Një djalë dhe një vajzë qëndrojnë pranë bankës me libër. Miqësia e tyre.",
    handwriting: "Sh sh  Shega sharra pisha",
  },
  {
    pageNumber: 23,
    title: "Shkronja Zz — Hëna mbi Zabel",
    letters: "Zz",
    text: [
      "HËNA MBI ZABEL",
      "",
      "Hëna u duk mbi zabel.",
      "— O, Zamirë, hënën e kanë zënë lisat e zabelit, — u ankua Zani.",
      "— Nënë, nënë, hëna u zu mbi zabel!",
      "— Kush do ta shpëtojë hënën nga degët e zabelit?! — pyeti prapë Zani me zemër të prekur.",
      "— Mos u pikëllo, Zani! Tash del hëna.",
      "Hëna u ngrit ngadalë mbi zabel. Ajo ndriçoi tërë fshatin me rreze të arta.",
      "Sa e bukur dukej hëna mbi zabel!",
    ],
    imageDescription:
      "Një djalë dhe një vajzë në ballkon shikojnë hënën mbi pemët e zabelit.",
    handwriting: "Z z  Zamiri zabeli zëri",
  },
  {
    pageNumber: 24,
    title: "Shkronja Vv — Në Vreshta",
    letters: "Vv",
    text: [
      "NË VRESHTA",
      "",
      "— Vu-vu! — niset treni e merr hov.",
      "Në vagonin e parë janë Valoni e Vala.",
      "Valoni ia nisi këngës. Pas tyre kënduan Visari, Vesa e Vetoni.",
      "Fëmijët arritën te vreshtat e vendit tonë.",
      "Mësuesi e fëmijët u ndihmuan vreshtarëve në vjeljen e rrushit.",
    ],
    imageDescription:
      "Fëmijë në vreshta duke vjelur rrush. Kodra në sfond, hardhi me rrush.",
    handwriting: "V v  Vetoni voli plot rrush.  Valoni shkoi në vreshtë.",
  },
  {
    pageNumber: 25,
    title: "Shkronja Qq — Nëna Qëndresë",
    letters: "Qq",
    text: [
      "NËNA QËNDRESË",
      "",
      "Nëna Qamile e kishte djalin në arrati. Armiqtë ia sulmuan shtëpinë.",
      "— Ku e ke djalin? — e pyetën nënën Qamile.",
      "Ajo nuk u tregoi.",
      "Armiqtë i ranë në qafë.",
      "Nëna i pështyu në fytyrë e i quajti qen.",
      "Armiqtë u tërbuan. E përplasën nënën Qamile për dysheme.",
      "— Trego, ku e ke djalin?",
      "Nëna duroi shumë. Populli e quajti Nëna Qëndresë.",
    ],
    imageDescription:
      "Dy ushtarë me pushkë përballojnë një grua të moshuar me shami. Dritarja me shkronjat Qq.",
    handwriting: "Q q  Qerimi qeni qafa",
  },
  {
    pageNumber: 26,
    title: "Shkronja DHdh — Dhëmballa",
    letters: "DHdh",
    text: [
      "DHËMBALLA",
      "",
      "Dhurimit i dhemb dhëmballa. Nëna e dërgoi te mjekja e dhëmbëve.",
      "— Ulu në karrige dhe mos u frikëso! — e qetësoi mjekja. — Hape mirë gojën!",
      "Dhurimi bëri si kërkoi mjekja.",
      "Dhëmballa e Dhurimit ishte prishur.",
      "— Këtë do ta shërojmë, por ki kujdes të mos prishen edhe dhëmbët e tjerë.",
      "— Po ç'të bëj unë? — pyeti Dhurimi.",
      "— Ti duhet t'i lash dhëmbët për çdo ditë. Dhëmbët lahen me brushë dhe pastë dhëmbësh, — i tregoi mjekja.",
      "Dhurimi falënderoi mjeken. Ai tash i lan dhëmbët rregullisht.",
    ],
    imageDescription:
      "Dentistja kontrollon dhëmbët e fëmijës. Mjete dentare mbi tryezë.",
    handwriting: "Dh dh  Dhurimi dhëmbi",
  },
  {
    pageNumber: 27,
    title: "Shkronja NJnj — Pulla e Njomzës",
    letters: "NJnj",
    text: [
      "PULLA E NJOMZËS",
      "",
      "Njomza shkon në klasë të parë. Nëna e saj punon në një fabrikë.",
      "Një ditë Njomza mori pallton për ta veshur. Ajo pa se i kishte rënë një pullë.",
      "Nëna nuk ishte në shtëpi. Kush do t'ia qepte pullën?",
      "— Do ta qep vetë, — mendoi Njomza.",
      "Ajo qepi pullën me kujdes.",
      "— Sa bukur! — u gëzua nëna. — Vajza ime ditka të qepë vetë!",
    ],
    imageDescription:
      "Një vajzë ulet pranë tryezës duke qepur pullën. Një çantë shkolle varur te dera.",
    handwriting: "Nj nj  Njomza njolla një",
  },
  {
    pageNumber: 28,
    title: "Shkronja GJgj — Zogjtë e Gjeraqinës",
    letters: "GJgj",
    text: [
      "ZOGJTË E GJERAQINËS",
      "",
      "Gjeraqina vizaton bukur. Zogjtë i vizaton si të ishin të gjallë.",
      "Në një fletë ka vizatuar gjashtë zogj. Ata janë me ngjyra të ndryshme.",
      "Prindërit e Gjeraqinës krenohen çdoherë:",
      "— Vajza jonë vizaton bukur.",
      "Gjeraqina vrapon t'i sjellë vizatimet.",
      "— Oh, sa bukur! — habiten ata që i shohin. — Gjeraqina paska një kopsht me plot zogj!",
    ],
    imageDescription:
      "Familja shikon vizatimet e Gjeraqinës me zogj shumëngjyrësh. Prindërit ulur në kolltukë.",
    handwriting: "Gj gj  Gjeraqina zogjtë gjyshi",
  },
  {
    pageNumber: 29,
    title: "Shkronja THth — Vjersha Thuhet me Zemër",
    letters: "THth",
    text: [
      "VJERSHA THUHET ME ZEMËR",
      "",
      "Të gjithë thonë se Thesari është recituesi më i mirë i klasës.",
      "Ai e thotë vjershën për mrekulli.",
      "— Thesar, kush të mëson të recitosh? — e pyetën një ditë shokët.",
      "— Unë bëj ushtrime. Përpiqem ta kuptoj mirë vjershën.",
      "Vjersha recitohet me zemër, — tha Thesari.",
      "Thesari do ta thotë një vjershë para prindërve.",
      "Po, Thesari do të recitojë në emisionet e fëmijëve.",
      "Aty do ta shohim e do ta dëgjojmë të gjithë.",
    ],
    imageDescription:
      "Tri fëmijë para televizorit ku shfaqet një djalë duke recituar.",
    handwriting: "Th th  Thesari thana gjethi",
  },
  {
    pageNumber: 30,
    title: "Shkronja Xx — Guxim, Anduena",
    letters: "Xx",
    text: [
      "GUXIM, ANDUENA",
      "",
      "Mësuesja nxori litarin. Atë e mbajtën dy veta. Të tjerët kërcyen.",
      "Vetëm Anduena nuk guxoi.",
      "— Provo përsëri! — i jepte guxim mësuesja.",
      "Anduena merrte hov, por kot.",
      "Mësuesja uli litarin fare poshtë.",
      "— Oh, këtë mund ta kërcej me sy mbyllur! — tha Anduena dhe vërtet e kapërceu.",
      "— Çojeni pak litarin. Nxito, Anduena! Guxim!",
      "Anduena vrapoi. U habit kur e pa veten matanë litarit.",
      "— Të lumtë, Anduena! — e lavdëruan shokët e shoqet.",
    ],
    imageDescription:
      "Fëmijë kërcejnë litarin në oborrin e shkollës. Mësuesja i mbikëqyr.",
    handwriting: "X x  Xixat xixëlluan",
  },
  {
    pageNumber: 31,
    title: "Shkronja XHxh — Xha Tafa",
    letters: "XHxh",
    text: [
      "XHA TAFA",
      "",
      "Xha Tafa është xhamaprerës. Ai i pret xhamat me shumë kujdes.",
      "Një ditë, i biri i tij, Jetoni, i erdhi në dyqan. Edhe ai deshi të presë xhama.",
      "— Jo, Jeton! — i tha i ati. — Ti je ende i vogël.",
      "Me xhama duhet të jesh shumë i kujdesshëm.",
      "Ata thyhen shpejt dhe nuk ngjiten më.",
      "Përveç kësaj, mund të pritesh e të të dalë gjak.",
      "Jetoni e la xhamin.",
    ],
    imageDescription:
      "Xha Tafa pret xhamin me kujdes. Jetoni qëndron pranë tryezës me xhama.",
    handwriting: "Xh xh  Xha Tafa pret xhama.",
  },
  {
    pageNumber: 32,
    title: "Shkronja ZHzh — Klasa Zhurmëtare",
    letters: "ZHzh",
    text: [
      "KLASA ZHURMËTARE",
      "",
      "Ka dy ditë që në klasën fqinje mungon mësuesja.",
      "Aty dëgjohet vazhdimisht diçka që bën zhu-zhu.",
      "Kjo është zhurma e nxënësve.",
      "Këtë klasë ne e quajtëm klasë zhurmëtare.",
      "— Sa keq! — na tha sot mësuesja jonë.",
      "— Nxënësit e mirë nuk bëjnë zhurmë as atëherë kur mungon mësuesja.",
      "Më vjen mirë që ju jeni të qetë.",
      "Ju mund të mësoni edhe pa mua.",
      "",
      "Zilja ra. Të gjithë dolëm në rresht.",
      "Ne nuk do të lejojmë kurrë që klasa jonë të bëhet klasë zhurmëtare.",
    ],
    imageDescription:
      "Klasa me nxënës në banka. Mësuesja qëndron e bën me shenjë.",
    handwriting: "Zh zh  Zhurma pengon mësimin.",
  },
]
